export const s = {
  body: {
    backgroundColor: "#f6f7f9",
    color: "#20242b",
    fontFamily: "Arial, Helvetica, sans-serif",
    margin: 0,
    padding: "32px 12px",
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    maxWidth: "600px",
    padding: "0 40px",
  },
  header: { padding: "42px 0 28px", borderBottom: "1px solid #e5e7eb" },
  wordmark: {
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "3px",
    margin: "0 0 34px",
  },
  eyebrow: {
    color: "#89919b",
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "1.6px",
    margin: "0 0 10px",
  },
  title: {
    fontFamily: "Georgia, Times New Roman, serif",
    fontSize: "34px",
    fontWeight: "400",
    letterSpacing: "-0.7px",
    lineHeight: "1.12",
    margin: "0 0 13px",
  },
  meta: { color: "#68717d", fontSize: "13px", margin: 0 },
  greeting: { color: "#68717d", fontSize: "14px", margin: "25px 0 0" },
  digest: { padding: "34px 0 0" },
  chip: {
    borderRadius: "4px",
    display: "inline-block",
    fontSize: "11px",
    fontWeight: "700",
    letterSpacing: "0.4px",
    margin: "0 0 15px",
    padding: "6px 9px",
  },
  headline: {
    fontFamily: "Georgia, Times New Roman, serif",
    fontSize: "24px",
    fontWeight: "400",
    lineHeight: "1.22",
    margin: "0 0 14px",
  },
  paragraph: {
    color: "#454d57",
    fontSize: "15px",
    lineHeight: "1.65",
    margin: 0,
  },
  conflictPanel: {
    backgroundColor: "#fff7e8",
    borderRadius: "5px",
    margin: "22px 0 12px",
    padding: "15px 17px",
  },
  signalPanel: {
    backgroundColor: "#edf8f1",
    borderRadius: "5px",
    margin: "22px 0 12px",
    padding: "15px 17px",
  },
  conflictLabel: {
    color: "#a47320",
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "1.3px",
    margin: "0 0 7px",
  },
  signalLabel: {
    color: "#347a51",
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "1.3px",
    margin: "0 0 7px",
  },
  panelText: {
    color: "#4b463b",
    fontSize: "14px",
    lineHeight: "1.55",
    margin: 0,
  },
  sourcesLabel: {
    color: "#89919b",
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "1.4px",
    margin: "28px 0 14px",
  },
  article: {
    borderBottom: "1px solid #eef0f2",
    padding: "0 0 13px",
    margin: "0 0 13px",
  },
  articleTitle: {
    color: "#2f5f91",
    display: "block",
    fontSize: "14px",
    fontWeight: "700",
    lineHeight: "1.4",
    textDecoration: "none",
  },
  articleSummary: {
    color: "#77808b",
    fontSize: "13px",
    lineHeight: "1.5",
    margin: "4px 0 0",
  },
  published: { color: "#a5abb2" },
  readLink: {
    color: "#2f5f91",
    display: "inline-block",
    fontSize: "14px",
    fontWeight: "700",
    margin: "4px 0 0",
    textDecoration: "none",
  },
  divider: { borderColor: "#e5e7eb", margin: "36px 0 0" },
  empty: { padding: "48px 0 62px" },
  emptyTitle: {
    fontFamily: "Georgia, Times New Roman, serif",
    fontSize: "22px",
    margin: "0 0 10px",
  },
  footer: {
    borderTop: "1px solid #e5e7eb",
    padding: "28px 0 40px",
    textAlign: "center" as const,
  },
  footerLinks: { fontSize: "12px", margin: "0 0 12px" },
  footerLink: { color: "#68717d", textDecoration: "underline" },
  copyright: { color: "#a0a6ad", fontSize: "11px", margin: 0 },
};

export const chipColors = [
  { backgroundColor: "#eee8ff", color: "#6046b8" },
  { backgroundColor: "#e5f5ed", color: "#26734d" },
  { backgroundColor: "#fff2d7", color: "#94651c" },
  { backgroundColor: "#ffe9e3", color: "#a44d38" },
  { backgroundColor: "#e4f0fb", color: "#32658f" },
];
